export const legends = [
  {
    id: 1,
    name: `Bangalore`,
    url: "https://media.contentapi.ea.com/content/dam/apex-legends/common/legends/apex-section-bg-legends-bangalore-xl.jpg.adapt.320w.jpg",
    classified: [`Assault`],
    cute: false,
  },
  {
    id: 2,
    name: `Revenant`,
    url: "https://media.contentapi.ea.com/content/dam/apex-legends/common/legends/apex-section-bg-legends-revenant-xl.jpg.adapt.320w.jpg",
    classified: [`Assault`],
    cute: false,
  },
  {
    id: 3,
    name: "Wraith",
    url: "https://media.contentapi.ea.com/content/dam/apex-legends/common/legends/apex-section-bg-legends-wraith-xl.jpg.adapt.320w.jpg",
    classified: [`Runner`],
    cute: false,
  },
  {
    id: 4,
    name: "Pathfinder",
    url: "https://media.contentapi.ea.com/content/dam/apex-legends/common/legends/apex-section-bg-legends-pathfinder-xl.jpg.adapt.320w.jpg",
    classified: [`Runner`],
    cute: false,
  },
  {
    id: 5,
    name: "Octane",
    url: "https://media.contentapi.ea.com/content/dam/apex-legends/common/legends/apex-section-bg-legends-octane-xl.jpg.adapt.320w.jpg",
    classified: [`Runner`],
    cute: false,
  },
  {
    id: 7,
    name: "Bloodhound",
    url: "https://media.contentapi.ea.com/content/dam/apex-legends/common/legends/apex-section-bg-legends-bloodhound-xl.jpg.adapt.320w.jpg",
    classified: [`Reacon`],
    cute: false,
  },
  {
    id: 8,
    name: "Loba",
    url: "https://media.contentapi.ea.com/content/dam/apex-legends/common/legends/apex-section-bg-legends-loba-xl.jpg.adapt.320w.jpg",
    classified: [`Support`],
    cute: true,
  },
  {
    id: 9,
    name: "Wattson",
    url: "https://media.contentapi.ea.com/content/dam/apex-legends/common/legends/apex-section-bg-legends-wattson-xl.jpg.adapt.320w.jpg",
    classified: [`Pioneer`],
    cute: false,
  },
];
